apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/jannfis/appset-testapp
          revision: HEAD
          files:
          - path: appset/apps.yaml
      - list:
          elementsYaml: "{{ .apps | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/jannfis/appset-testapp
        targetRevision: HEAD
        path: app
      destination:
        name: in-cluster
        namespace: test-{{.name}}
      syncPolicy:
        automated:
          enabled: true
        syncOptions:
        - CreateNamespace=true
